### PR TITLE
Fix for Kibana 4.6 + Logout button

### PR DESCRIPTION
**Pull request by lmangani**

### CODE REVIEW

**Comment by lmangani** [comment]
kibana-auth-plugin

**Comment by MiLk** [comment]
LGTM

**Comment by hmalphettes** [comment]
@lmangani much appreciated.

I am afraid I am not using this module for my projects nowadays.

If it helps you and probably the rest of the community, I can grant you write access to this repository or transfer it all together.

Let me know.

**Comment by lmangani** [comment]
Thanks @hmalphettes 
My team would be happy to take over extending and maintaining the plugin, feel free to transfer it to Elasticfence or drop me a message lorenzo.mangani@gmail.com anytime to arrange things :)

**Comment by nguoianphu** [comment]
Excellent! Thanks all. :+1:

**Pull request merged**
